apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-microservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: identitymicroservice
  template:
    metadata:
      labels:
        app: identitymicroservice
    spec:
      containers:
      - name: identity
        image: identitymicroservice.azurecr.io/amiltonr/identitymicroservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: identity-microservice-svc
spec:
  selector:
    app: identitymicroservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer